---
title: "DATA 608 STORY 3-Do stricter gun laws reduce firearm gun deaths?"
author: "Yina Qiao"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# API
```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(plotly)

```

```{r, eval=FALSE}
url <- "https://data.cdc.gov/resource/489q-934x.json"

response <- GET(url)

if (status_code(response) == 200) {

  data <- fromJSON(content(response, "text", encoding = "UTF-8"))
  
  df_mortality <- as.data.frame(data)
  
  
} else {
  cat("Error: Unable to retrieve data from the URL.\n")
}

head(df_mortality)
```

```{r, echo=FALSE}
# Check if mortality_cache.rds exists, if not create it with df_mortality data
if (!file.exists("mortality_cache.rds")) {
  saveRDS(df_mortality, "mortality_cache.rds")
} else {
  df_mortality <- readRDS("mortality_cache.rds")
}

```

# Data Prep
```{r,message=FALSE, warning=FALSE}
# overview of data
# unique_values_year_and_quarter <- unique(df_mortality$year_and_quarter)
# unique_values_cause_of_death <- unique(df_mortality$cause_of_death)
# unique_values_time_period <- unique(df_mortality$time_period)
# unique_values_rate_type <- unique(df_mortality$rate_type)
# unique_values_cause_of_death
# unique_values_year_and_quarter
# unique_values_time_period
# unique_values_rate_type

df_gun <- df_mortality[df_mortality$cause_of_death == "Firearm-related injury", ]
df_gun <- df_gun[df_gun$rate_type == "Crude", ]
df_gun <- df_gun[df_gun$time_period == "12 months ending with quarter", ]
df_gun <- data.frame(df_gun, row.names = NULL)

state_abbreviations <- c(AL = "alabama", AK = "alaska", AZ = "arizona", AR = "arkansas", CA = "california", 
                         CO = "colorado", CT = "connecticut", DE = "delaware", FL = "florida", GA = "georgia", 
                         HI = "hawaii", ID = "idaho", IL = "illinois", IN = "indiana", IA = "iowa", 
                         KS = "kansas", KY = "kentucky", LA = "louisiana", ME = "maine", MD = "maryland", 
                         MA = "massachusetts", MI = "michigan", MN = "minnesota", MS = "mississippi", MO = "missouri", 
                         MT = "montana", NE = "nebraska", NV = "nevada", NH = "new_hampshire", NJ = "new_jersey", 
                         NM = "new_mexico", NY = "new_york", NC = "north_carolina", ND = "north_dakota", 
                         OH = "ohio", OK = "oklahoma", OR = "oregon", PA = "pennsylvania", RI = "rhode_island", 
                         SC = "south_carolina", SD = "south_dakota", TN = "tennessee", TX = "texas", UT = "utah", 
                         VT = "vermont", VA = "virginia", WA = "washington", WV = "west_virginia", WI = "wisconsin", 
                         WY = "wyoming", DC = "district_of_columbia")

# Loop through each state abbreviation
for (abbrev in names(state_abbreviations)) {
  pattern <- paste0("rate_", state_abbreviations[abbrev])
  colnames(df_gun) <- gsub(pattern, abbrev, colnames(df_gun))
}

# Data type conversion:  columns 6 to 69 are converted to double.
df_gun <- df_gun %>%
  mutate(across(.cols = 6:69, .fns = as.double))

df_gun <- df_gun %>%
  mutate(year = substr(year_and_quarter, 1, 4))%>%# Extract year
  group_by(year)

df_gun_2022 <- df_gun %>%
  filter(year_and_quarter == "2022 Q4")

# Piving Long
df_gun_2022_long <- df_gun_2022 %>%
                          pivot_longer(
                            cols = c(AK:WY),  # Specify the range of columns to pivot
                            names_to = "state",  # New column name
                            values_to = "rate"  # New column for values
                          )

final_df <- df_gun_2022_long %>%
  select(year, state, rate)

# Add gun law rank to final_df
final_df <- final_df %>%
  mutate(
    gun_laws = case_when(
      state %in% c("AK", "AL", "AR", "AZ", "GA", "IA", "ID", "IN", "KS", "KY", "LA", "ME", "MO", "MS", "MT", "ND", "NH", "OH", "OK", "SC", "SD", "TN", "TX", "UT", "WV", "WY") ~ "1",
      state == "WI" ~ "2",
      state %in% c("FL", "MI", "MN", "NC", "NE", "NM", "NV", "VT") ~ "3",
      state %in% c("CO", "DE", "OR", "PA", "RI", "VA", "WA") ~ "4",
      state %in% c("CA", "CT", "DC", "HI", "IL", "MA", "MD", "NJ", "NY") ~ "5",
      TRUE ~ NA_character_
    )
  )
final_df$gun_laws <- as.numeric(final_df$gun_laws)
final_df$year <- as.numeric(final_df$year)
final_df
# Check the structure and the first few rows of the final dataframe
#final_df_sorted <- final_df %>%
  #arrange(desc(rate))
#str(final_df)
#head(final_df_sorted)
#tail(final_df_sorted)

```


# Data Visuals
```{r, echo=FALSE,message=FALSE, warning=FALSE}
mortality_map <- plot_geo(final_df, locations = ~state, text = ~state, z = ~rate) %>%
  add_trace(
    type = "choropleth",
    colors = "Purples",
    locationmode = "USA-states",
    hovertemplate = 'State: %{location}<br>Mortality Rate: %{z}<extra></extra>'
  ) %>%
  colorbar(
    title = "Mortality Rate",
    len = 0.4,  # Length of the colorbar
    x = 0,  # X position of the colorbar
    y = -0.1,  # Y position of the colorbar
    xanchor = "left",
    yanchor = "bottom",
    titleside = "bottom",
    ticktext = c("Safest", "Deadliest"),
    tickvals = c(min(final_df$rate), max(final_df$rate)),
    orientation = "h"  # Horizontal orientation
  ) %>%
  layout(
    geo = list(
      scope = "usa",
      projection = list(type = "albers usa"),
      showlakes = TRUE,
      lakecolor = toRGB("white")
    )
  )

gun_laws_map <- plot_geo(final_df, locations = ~state, text = ~state, z = ~gun_laws) %>%
  add_trace(
    type = "choropleth",
    colorscale = "YlOrBr",
    locationmode = "USA-states",
    hovertemplate = 'State: %{location}<br>Gun Law Rank: %{z}<extra></extra>'
  ) %>%
  colorbar(
    title = "Gun Law Rank",
    len = 0.4,  # Length of the colorbar
    x = 0.5,  # X position of the colorbar, adjusted to be on the right side
    y = -0.1,  # Y position of the colorbar
    xanchor = "left",
    yanchor = "bottom",
    titleside = "bottom",
    ticktext = c("Weaker Law", "Stronger Law"),
    tickvals = c(min(final_df$gun_laws), max(final_df$gun_laws)),
    orientation = "h"  # Horizontal orientation
  ) %>%
  layout(
    geo = list(
      scope = "usa",
      projection = list(type = "albers usa"),
      showlakes = TRUE,
      lakecolor = toRGB("white")
    )
  )

subplot(mortality_map, gun_laws_map, nrows = 1, titleX = TRUE) %>%
  layout(
    title = "States with <b><span style='font-size: 27px;'>Stronger ↑</span></b> Gun Laws Have <b><span style='font-size:23px;'>Lower ↓</span></b> Rates of Gun Deaths",
    annotations = list(
      list(
        x = 0.5,
        y = 1,  # Adjust this value to position the subtitle correctly
        xref = "paper",
        yref = "paper",
        text = "Someone living in <b>Mississippi</b> was <b><span style='font-size: 27px;'>7.5x </span></b><b>more likely to die by gun violence</b> than someone living in <b>Massachusetts</b>",  # Your subtitle text here
        showarrow = FALSE,
        font = list(
          size = 14  # Adjust subtitle font size as needed
        ),
        xanchor = "center",
        yanchor = "bottom",
        align = "center"
      )
    ),
    margin = list(t = 150),  # Increase top margin to accommodate title and subtitle
    width = 1200,  # Width of the graph in pixels
    height = 650  # Height of the graph in pixels
  )
```






